django_proj/django_projects/rango_project/rango/urls.py
from django.urls import path
from rango import views
from django.conf.urls.static import static
from django.conf import settings

app_name='rango'
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('category/<slug:category_name_slug>/', views.show_category, name='show_category'),
    path('add_category/', views.add_category, name='add_category'),
    path('add_page/<slug:page_name_slug>/', views.add_page, name='add_page'),
] 

django_proj/django_projects/rango_project/rango_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('rango/', include('rango.urls')),
    path('accounts/', include('registration.backends.simple.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_proj/django_projects/rango_project/rango/models.py
from django.db import models
from django.template.defaultfilters import slugify

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes =models.IntegerField(default=0)
    slug = models.SlugField(default='', unique=True)

    def save(self, *args, **kwargs):
        self.slug=slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

class Page(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title

django_proj/django_projects/rango_project/rango/forms.py
from django import forms
from rango.models import Page, Category

class CategoryForm(forms.ModelForm):
    name= forms.CharField(max_length=128, help_text="Please enter a category name")
    views= forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes= forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes= forms.CharField(widget=forms.HiddenInput(), required=False)

    # An inline class to provide additional information on the form
    class Meta:
        # Provide an association between the ModelForm and a model
        model=Category
        fields=('name',)

class PageForm(forms.ModelForm):
    title=forms.CharField(max_length=128, help_text='Please enter the title of the page')
    url=forms.URLField(max_length=200, help_text='Please enter the URL of the page')
    views=forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        # Provide an association between the ModelForm and a model
        model = Page

        exclude = ('category', )
        # or specify the fields to include (i.e. not include the category field)
        #fields = ('title', 'url', 'views')
    
    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')
        # If url is not empty and doesn't start with 'http://',
        # then prepend 'http://'.
        if url and not url.startswith('http://'):
            url = 'http://' + url
            cleaned_data['url'] = url
            return cleaned_data

django_proj/django_projects/rango_project/rango/views.py
from django.shortcuts import render
from rango.models import Category, Page
from rango.forms import CategoryForm, PageForm
from datetime import datetime

# Create your views here.

def index(request):
    # Query the database for a list of ALL categories currently stored.
    # Order the categories by no. likes in descending order.
    # Retrieve the top 5 only - or all if less than 5.
    # Place the list in our context_dict dictionary
    # that will be passed to the template engine.
    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by('-views')[:5]
    context_dict = {'categories': category_list, 'pages': page_list}
    # Obtain our Response object early so we can add cookie information.
    response = render(request, 'rango/index.html', context_dict)
    # Call the helper function to handle the cookies
    visitor_cookie_handler(request, response)
    # Return response back to the user, updating any cookies that need changed.
    return response



def about(request):
    if request.session.test_cookie_worked():
        print("TEST COOKIE WORKED!")
        request.session.delete_test_cookie()
    return render(request, 'rango/about.html', {})

def show_category(request, category_name_slug):
    # Create a context dictionary which we can pass
    # to the template rendering engine.
    context_dict = {}
    try:
        # Can we find a category name slug with the given name?
        # If we can't, the .get() method raises a DoesNotExist exception.
        # So the .get() method returns one model instance or raises an exception.
        category = Category.objects.get(slug=category_name_slug)
        # Retrieve all of the associated pages.
        # Note that filter() will return a list of page objects or an empty list
        pages = Page.objects.filter(category=category)
        # Adds our results list to the template context under name pages.
        context_dict['pages'] = pages
        # We also add the category object from
        # the database to the context dictionary.
        # We'll use this in the template to verify that the category exists.
        context_dict['category'] = category
    except Category.DoesNotExist:
        # We get here if we didn't find the specified category.
        # Don't do anything -
        # the template will display the "no category" message for us.
        context_dict['category'] = None
        context_dict['pages'] = None
    
    # Go render the response and return it to the client.
    return render(request, 'rango/category.html', context_dict)

def add_category(request):
    form = CategoryForm()

    # A HTTP POST?
    if request.method=='POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print(form.errors)

    return render(request, 'rango/add_category.html', {'form': form})


def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category = None

    form = PageForm()
    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.save()
                return show_category(request, category_name_slug)
        else:
            print(form.errors)
            
    context_dict = {'form':form, 'category': category}
    return render(request, 'rango/add_page.html', context_dict)


def visitor_cookie_handler(request, response):
        # Get the number of visits to the site.
        # We use the COOKIES.get() function to obtain the visits cookie.
        # If the cookie exists, the value returned is casted to an integer.
        # If the cookie doesn't exist, then the default value of 1 is used.
        visits = int(request.COOKIES.get('visits', '1'))
        last_visit_cookie = request.COOKIES.get('last_visit', str(datetime.now()))
        last_visit_time = datetime.strptime(last_visit_cookie[:-7],
        '%Y-%m-%d %H:%M:%S')
        # If it's been more than a day since the last visit...
        if (datetime.now() - last_visit_time).days > 0:
            visits = visits + 1
            # Update the last visit cookie now that we have updated the count
            response.set_cookie('last_visit', str(datetime.now()))
        else:
            # Set the last visit cookie
            response.set_cookie('last_visit', last_visit_cookie)

        # Update/set the visits cookie
        response.set_cookie('visits', visits)

# A helper method
def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val


# Updated the function definition
def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request, 'visits', '1'))
    last_visit_cookie = get_server_side_cookie(request,
    'last_visit',
    str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7],
    '%Y-%m-%d %H:%M:%S')
    # If it's been more than a day since the last visit...
    if (datetime.now() - last_visit_time).days > 0:
        visits = visits + 1
        #update the last visit cookie now that we have updated the count
        request.session['last_visit'] = str(datetime.now())
    else:
        # set the last visit cookie
        request.session['last_visit'] = last_visit_cookie
    # Update/set the visits cookie
    request.session['visits'] = visits

django_proj/django_projects/rango_project/templates/rango/about.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>This tutorial has been put together by Jon</h1>
    <img src="{{MEDIA_URL}}cat.jpg" alt="Picture of doge" /> <!-- New line -->
    <img src="{% static 'images/rango.jpg' %}" alt="Picture of Rango" /> <!-- New line -->
</body>
</html>

django_proj/django_projects/rango_project/templates/rango/add_category.html
<html>

<head>
    <title>Rango</title>
</head>

<body>
    <h1>Add a category</h1>
    <div>
        <form id="category_form" method="POST" action="/rango/add_category/">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{hidden}}
            {% endfor %} 
       
            <div style="background-color:aqua; width:200px; height:100px">
            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}
                {{ field }}
            {% endfor %}
            </div>
            <input type="submit" name="submit" value="Create Category" />
        </form>

    </div>

</body>


</html>

django_proj/django_projects/rango_project/templates/rango/add_page.html
<html>

<head>
    <title>Rango</title>
</head>

<body>
    <h1>Add a Page</h1>
    <div>
        <form id="page_form" method="POST" action="/rango/add_page/">
            {% csrf_token %}
            <h2>{{category}}</h2>
            {% for hidden in form.hidden_fields %}
            {{hidden}}
            {% endfor %} 
       
            <div style="background-color:aqua; width:200px; height:100px">
            {% for field in form.visible_fields %}
            {{ field.errors }}
            {{ field.help_text }}
            {{ field }}
            {% endfor %}
            </div>
            <input type="submit" name="submit" value="Create page" />
        </form>

    </div>

</body>


</html>

django_proj/django_projects/rango_project/templates/rango/base.html
<!--DOCTYPE html-->

{% load static %}
{% load rango_template_tags %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Rango-
        {% block title_block %}
        - How to Tango with Django
        {% endblock %}
    </title>
</head>

<body>
    <div>
        {% block sidebar_block %}
        {% get_category_list category %}
        {% endblock %}
    </div>
    <div>
        <!--Page specific content goes here-->
        {% block body_block %}
        place holder block content
        {% endblock %}
    </div>
    <hr>
    <div>
        <ul>
            <li><a href="{% url 'rango:add_category' %}">Add new Category</a></li>
            <li><a href="{% url 'rango:about' %}">About</a></li>
            <li><a href="{% url 'rango:index' %}">Index</a></li>
        </ul>
    </div>
</body>

</html>

django_proj/django_projects/rango_project/templates/rango/categories.html
<ul class="nav nav-sidebar">
    {% if categories %}
        {% for c in categories %}
            {% if c == act_cat %}
                <strong><li class="active">{{ c.name }}</li></strong>
            {% else %}
                <li>
            {% endif %}
        <a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a></li>
    {% endfor %}
    {% else %}
    <li> <strong>There are no category present.</strong></li>
    {% endif %}
</ul>

django_proj/django_projects/rango_project/templates/rango/category.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}
    {{ category.name }}
{% endblock %}

{% block body_block %}
    {% if category %}
         <h1>{{category.name}}</h1>
        {% if pages %}
            <ul>
                {% for page in pages %}
                <li><a href="{{ page.url }}">{{ page.title }}</a></li>
                {% endfor %}
            </ul>
                {% else %}
                        <strong>No page currently in category</strong>
                {% endif %}
                <a href="{% url 'rango:add_page' category.slug %}">Add a New Page</a><br />
            {% else %}
                The Specified category does not exist
            {% endif %}
        {% endblock %}

django_proj/django_projects/rango_project/templates/rango/index.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <title>Rango</title>
</head>

<body>
    <h1>Rango says...</h1>
    <div>
        hey there partner! <br />
        <strong>{{ boldmessage }}</strong>
    </div>
    <div>
        <h1>Most Liked Categories</h1>
        {% if categories %}
        <ul>
            {% for category in categories %}
            <li>
                <a href="{% url 'rango:show_category' category.slug %}">{{ category.name }}</a>
            </li>
            {% endfor %}

        {% else %}
        <strong>There are no categories present.</strong>
        {% endif %}

        <br>
        <h1>Most Viewed page</h1>
        {% if pages %}
        <ul>
            {% for page in pages %}
            <li>
                <a href="">{{ page.title }}</a>
            </li>
            {% endfor %}
        </ul>
        {% else %}
        <strong>There are no pages present</strong>
        {% endif %}

    </div>
    <div>
        <a href="/rango/add_category/">Add a New Category</a><br />
        <a href="{% url 'rango:about' %}">About Rango</a><br />
        <img src="{% static 'images/rango.jpg' %}" alt="Picture of Rango" />
    </div>
</body>

</html>